"""What the explorer's read surface must keep answering.

These pin the four things §20 asks a front end to render faithfully — a binary
cross-source relation, a ternary semantic assertion with every role intact, an
unresolved obligation that is not a denial, and derived state distinguishable
from base — plus the rule that makes the adapter safe to keep: it holds nothing.

The world is built once per session from the sealed research path, into a tmp
directory. Building rather than reading `data/worlds/` on purpose: a test that
depends on a file someone generated by hand passes for reasons it cannot state.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from research.semantic_integration.domains.bom.operational_frontier.generate import (
    freeze_operational_frontier,
)
from research.semantic_integration.domains.bom.world_programming.construct import (
    construct_experimental_world,
)
from world_explorer.adapter import WorldExplorerAdapter


@pytest.fixture(scope="module")
def world_path(tmp_path_factory) -> Path:
    path = tmp_path_factory.mktemp("world") / "bomS1.sqlite"
    experimental = construct_experimental_world(path)
    freeze_operational_frontier(
        experimental.world.taskview, path.with_suffix(".demand.json")
    )
    experimental.world.close()
    return path


@pytest.fixture
def adapter(world_path: Path):
    with WorldExplorerAdapter(world_path) as opened:
        yield opened


def test_opens_without_being_told_the_view_id(world_path: Path):
    # The id belongs to the file. Requiring the caller to know it is how opening
    # a world becomes a guess that fails as if the file were corrupt.
    with WorldExplorerAdapter(world_path) as opened:
        assert opened.overview()["world_id"] == "bom-semantic-integration-c1"


def test_overview_accounts_for_every_assertion_by_construction_origin(adapter):
    overview = adapter.overview()
    assert overview["origins"]["SEMANTIC"] == 2
    assert overview["origins"]["MECHANICAL"] > 0
    assert overview["origins"]["DERIVED"] > 0
    assert sum(overview["origins"].values()) == overview["assertions"]
    assert "UNKNOWN" not in overview["origins"]


def test_schema_carries_the_facts_the_projection_needs(adapter):
    schema = {record["name"]: record for record in adapter.schema()}

    # §20 binary cross-source relation: collapses onto a filament.
    assert schema["listing_of"]["arity"] == 2

    # §20 ternary: three roles, all referents, none of them dropped.
    ternary = schema["acceptable_replacement"]
    assert ternary["arity"] == 3
    assert [role["name"] for role in ternary["roles"]] == [
        "new_part",
        "old_part",
        "context",
    ]
    assert all(role["referent"] for role in ternary["roles"])

    # A scalar role must be distinguishable, or §5.4 cannot decide what becomes
    # a card field instead of a node.
    assert any(not role["referent"] for role in schema["rated_voltage"]["roles"])


def test_role_kinds_are_observed_not_declared(adapter):
    """§7.1 is drawn in kinds the schema does not have.

    A role is typed REFERENT and nothing more, so `Part ─ listing_of ─
    SupplierListing` has to come from the ids the role has actually been filled
    with. Observation, not schema — and a role nothing has filled reports
    nothing rather than inventing a type the world never asserted.
    """
    schema = {record["name"]: record for record in adapter.schema()}
    kinds = {
        role["name"]: role["kinds"] for role in schema["listing_of"]["roles"]
    }
    assert kinds == {"listing": ["listing"], "part": ["part"]}

    ternary = {role["name"]: role["kinds"] for role in schema["acceptable_replacement"]["roles"]}
    assert ternary["context"] == ["context"]
    assert ternary["new_part"] == ternary["old_part"] == ["part"]

    # A scalar role has no kind at all — it never becomes a disc.
    scalar = next(
        role for role in schema["rated_voltage"]["roles"] if not role["referent"]
    )
    assert scalar["kinds"] == []


def test_derived_state_is_distinguishable_and_names_its_inputs(adapter):
    schema = {record["name"]: record for record in adapter.schema()}
    eligible = schema["eligible_part"]
    assert eligible["mode"] == "DERIVED"
    assert set(eligible["derivation"]["inputs"]) == {
        "lifecycle",
        "temperature_compatible",
        "voltage_compatible",
    }
    assert schema["listing_of"]["mode"] == "BASE"


def test_schema_names_origin_and_completeness_for_the_overlay(adapter):
    """§9's SHOW and overlay read facts off the schema, not off the canvas.

    Construction origin is who decided the tuples — SHOW's four layers — and
    completeness is a claim about a relation, or absent. A missing receipt is
    not UNKNOWN; UNKNOWN is a status someone recorded. The BOM fixture has
    COMPLETE receipts on derived relations and none on BASE ones, and nothing
    is stale until an input moves.
    """
    schema = {record["name"]: record for record in adapter.schema()}
    assert schema["acceptable_replacement"]["origins"] == ["SEMANTIC"]
    assert schema["listing_of"]["origins"] == ["MECHANICAL"]
    assert schema["eligible_part"]["origins"] == ["DERIVED"]

    complete = schema["eligible_part"]["completeness"]
    assert complete["status"] == "COMPLETE"
    assert complete["current"] is True
    assert complete["universe"]
    assert schema["listing_of"]["completeness"] is None

    overview = adapter.overview()
    assert overview["incomplete"] == []
    assert overview["stale"] == []


def test_schema_sees_staleness_after_an_input_moves(world_path: Path, tmp_path):
    """The overlay's input: an input that has moved makes the derived relation stale.

    The derivation drawer already accounts for this per input. The canvas
    needs the same fact at relation grain, or it is still just a flag in a
    panel. Copied rather than mutated in place: the module-scoped world is
    everyone else's fixture.
    """
    from research.semantic_integration.core.origins import ConstructionOrigin

    copy = tmp_path / "stale.sqlite"
    copy.write_bytes(world_path.read_bytes())
    origins = Path(str(world_path) + ".origins.json")
    if origins.exists():
        Path(str(copy) + ".origins.json").write_bytes(origins.read_bytes())

    with WorldExplorerAdapter(copy) as opened:
        eligible = next(item for item in opened.schema() if item["name"] == "eligible_part")
        assert eligible["stale"] is False

        rated = next(item for item in opened.schema() if item["name"] == "rated_voltage")
        referent = next(role["name"] for role in rated["roles"] if role["referent"])
        scalar = next(role["name"] for role in rated["roles"] if not role["referent"])
        opened._world.add_referent("part:ZZZ-stale", label="stale-probe")
        opened._world.assert_tuple(
            "rated_voltage",
            {referent: "part:ZZZ-stale", scalar: 1},
            origin=ConstructionOrigin.MECHANICAL,
        )

        moved = next(item for item in opened.schema() if item["name"] == "eligible_part")
        assert moved["stale"] is True
        assert "eligible_part" in opened.overview()["stale"]
        # Completeness stays the last declared status — stale is a different fact.
        assert moved["completeness"]["status"] == "COMPLETE"
        assert moved["completeness"]["current"] is False


def test_dependency_closure_runs_both_ways_from_any_relation(adapter):
    # §8.6 asks what a derived relation rests on; §21 asks what depends on a
    # thing, which is the same edge read backwards. A base relation has no
    # derivation and must still answer the second question.
    up = adapter.derivation("eligible_part")
    assert up["rests_on"]["eligible_part"] == [
        "lifecycle",
        "temperature_compatible",
        "voltage_compatible",
    ]
    # Transitive, not one hop: the compatibility relations are themselves
    # derived, and the closure reaches what they read.
    assert "rated_voltage" in up["rests_on"]["voltage_compatible"]
    assert up["nodes"]["rated_voltage"]["mode"] == "BASE"
    assert up["supports"] == {}

    down = adapter.derivation("rated_voltage")
    assert down["run"] is None
    assert down["rests_on"] == {}
    assert down["supports"]["rated_voltage"] == ["spec_conflict", "voltage_compatible"]
    assert down["supports"]["voltage_compatible"] == ["eligible_part"]


def test_a_relation_reached_twice_is_one_node_with_one_edge_list(adapter):
    # `part_type` feeds both compatibility relations, so the walk arrives at it
    # along two paths. Adjacency, not a nested tree, is what keeps that one fact.
    closure = adapter.derivation("eligible_part")
    assert "part_type" in closure["rests_on"]["voltage_compatible"]
    assert "part_type" in closure["rests_on"]["temperature_compatible"]
    assert len(closure["nodes"]) == len(set(closure["nodes"]))
    for reached in closure["rests_on"].values():
        assert len(reached) == len(set(reached))


def test_the_run_record_compares_every_input_against_the_relation_now(adapter):
    run = adapter.derivation("eligible_part")["run"]
    assert run["state"] == "SUCCEEDED"
    assert "FROM voltage_compatible" in run["sql"]
    inputs = {item["relation"]: item for item in run["inputs"]}
    # Nothing has moved in a world nobody has written to since it was compiled,
    # so staleness has an account and the account is "current".
    assert all(not item["moved"] for item in inputs.values())
    assert inputs["voltage_compatible"]["version_at_run"] == inputs[
        "voltage_compatible"
    ]["version_now"]
    # The engine snapshots inputs the dependency table does not declare. That
    # difference is reported rather than merged away.
    assert inputs["lifecycle"]["declared"] is True
    assert inputs["bom_item"]["declared"] is False


def test_tuple_level_support_is_offered_as_candidates_not_lineage(adapter):
    # No table in this world records which input rows produced an output row.
    # What can be answered is which input tuples mention the same referents,
    # and the ranking says how many — never that they are the cause.
    derived = adapter.rows("eligible_part", limit=1)["rows"][0]
    support = adapter.derivation_support(derived["assertion_id"])
    assert support["derived"] is True
    assert support["referents"] == [
        derived["values"]["part"],
        derived["values"]["bom_item"],
    ]
    inputs = {item["relation"]: item for item in support["inputs"]}
    assert set(inputs) == {"lifecycle", "temperature_compatible", "voltage_compatible"}
    # The two-referent inputs match on both roles; lifecycle only carries the
    # part, so it can only ever mention one.
    assert inputs["voltage_compatible"]["tuples"][0]["mentions"] == 2
    assert inputs["lifecycle"]["tuples"][0]["mentions"] == 1
    assert inputs["lifecycle"]["tuples"][0]["values"]["part"] == derived["values"]["part"]
    # Capped: an explanation that returns the whole extension is an extension.
    for item in support["inputs"]:
        assert len(item["tuples"]) <= adapter.MAX_SUPPORT
        assert item["matched"] >= len(item["tuples"])


def test_support_of_a_base_assertion_says_so_rather_than_guessing(adapter):
    base = adapter.rows("rated_voltage", limit=1)["rows"][0]
    support = adapter.derivation_support(base["assertion_id"])
    assert support["derived"] is False
    assert support["inputs"] == []


def test_referent_separates_card_fields_from_relations_and_counts_them(adapter):
    referent = adapter.referent("part:X160")
    fields = {field["relation"]: field["value"] for field in referent["fields"]}
    assert fields["rated_voltage"] == 24
    assert fields["lifecycle"] == "discontinued"

    # Every card field is still an assertion — the inspector has to be openable
    # on it, or §5.4's convenience has quietly reinstated a property bag.
    for field in referent["fields"]:
        assert adapter.assertion(field["assertion_id"])["values"]

    relations = {item["name"]: item["count"] for item in referent["relations"]}
    assert relations["acceptable_replacement"] == 1
    assert "rated_voltage" not in relations


def test_assertion_exposes_origin_grounding_and_source_pointers(adapter):
    rows = adapter.rows("acceptable_replacement")["rows"]
    outdoor = next(
        row for row in rows if row["values"]["context"] == "context:outdoor_enclosure"
    )
    detail = adapter.assertion(outdoor["assertion_id"])

    assert detail["origin"] == "SEMANTIC"
    assert detail["values"] == {
        "new_part": "part:X110",
        "old_part": "part:X160",
        "context": "context:outdoor_enclosure",
    }

    # §8.5: a reader must get the file and the place in it, not a JSON string.
    pointers = {
        (item.get("native_handle"), item.get("native_location"))
        for item in detail["grounding"]
        if item["kind"] == "SOURCE"
    }
    assert ("bom.csv", "row 2 (bom_item=BOM-A)") in pointers
    assert ("engineering_notes.md", "lines 6-14 (ER-1)") in pointers


def test_unresolved_obligation_is_not_a_denial(adapter):
    demand = adapter.demand()
    assert demand["purpose"]["id"] == "viable_replacement"
    unresolved = [
        item for item in demand["obligations"] if item["state"] == "UNRESOLVED"
    ]
    assert {"new_part": "part:X110", "old_part": "part:X160", "context": "context:indoor_panel"} in [
        item["values"] for item in unresolved
    ]
    # The world holds no tuple for it, and the frontier says so without the
    # relation acquiring a false one.
    assert all(item["assertion_id"] is None for item in unresolved)


def test_a_met_obligation_names_the_assertion_that_meets_it(world_path: Path, tmp_path):
    """A frontier is only readable if it says what has been answered, too.

    The obligation set is a claim about what some purpose wanted, not a second
    kind of tuple, so an obligation the world does answer has to resolve to the
    *real* assertion — the one with grounding and an origin — rather than to a
    second record of the same fact. That is what lets the front end draw a met
    obligation as an ordinary assertion and an unmet one as a hollow mark.
    """
    met = tmp_path / "met.sqlite"
    met.write_bytes(world_path.read_bytes())
    origins = world_path.with_suffix(".sqlite.origins.json")
    if origins.exists():
        met.with_suffix(".sqlite.origins.json").write_bytes(origins.read_bytes())
    document = json.loads(world_path.with_suffix(".demand.json").read_text())
    answered = {
        "new_part": "part:X110",
        "old_part": "part:X160",
        "context": "context:outdoor_enclosure",
    }
    document["obligations"].append(
        {
            "demanded_by": {"kind": "purpose", "name": "viable_replacement", "revision": 1},
            "relation": "acceptable_replacement",
            "values": answered,
        }
    )
    met.with_suffix(".demand.json").write_text(json.dumps(document))

    with WorldExplorerAdapter(met) as opened:
        obligations = opened.demand()["obligations"]
        asserted = [item for item in obligations if item["state"] == "ASSERTED"]
        assert [item["values"] for item in asserted] == [answered]
        found = opened.assertion(asserted[0]["assertion_id"])
        assert found["relation"] == "acceptable_replacement"
        assert found["values"] == answered
        # And the unmet one is still unmet: answering a sibling case does not
        # quietly answer the case nobody asserted.
        assert any(item["state"] == "UNRESOLVED" for item in obligations)


def test_demand_is_absent_rather_than_empty_without_a_purpose(world_path: Path, tmp_path):
    bare = tmp_path / "bare.sqlite"
    bare.write_bytes(world_path.read_bytes())
    with WorldExplorerAdapter(bare) as opened:
        # No purpose loaded is not the same claim as no open questions.
        assert opened.demand() is None


def test_rows_page_and_order_in_sql(adapter):
    first = adapter.rows("temperature_compatible", limit=1, order="part")
    second = adapter.rows("temperature_compatible", limit=1, offset=1, order="part")
    assert first["total"] > 1
    assert len(first["rows"]) == 1
    assert first["rows"][0]["assertion_id"] != second["rows"][0]["assertion_id"]
    assert first["rows"][0]["values"]["part"] <= second["rows"][0]["values"]["part"]

    descending = adapter.rows("temperature_compatible", limit=1, order="part", descending=True)
    assert descending["rows"][0]["values"]["part"] >= first["rows"][0]["values"]["part"]


def test_rows_narrow_to_one_referent(adapter):
    """A table opened from a referent answers about that referent.

    The panel offers a relation by the referent's own count, so the extension
    behind that offer has to be the same set — narrowed *and* counted, since a
    windowed table sizes itself from the total before a row has arrived.
    """
    whole = adapter.rows("temperature_compatible", limit=500)
    subject = whole["rows"][0]["values"]["part"]
    narrowed = adapter.rows("temperature_compatible", limit=500, subject=subject)

    assert narrowed["total"] < whole["total"]
    assert narrowed["total"] == len(narrowed["rows"])
    assert all(row["values"]["part"] == subject for row in narrowed["rows"])
    # The same predicate `expand` uses, so the two surfaces cannot disagree
    # about what a referent takes part in.
    assert narrowed["total"] == len(
        adapter.expand(subject, "temperature_compatible")["tuples"]
    )


def test_rows_narrowed_by_a_stranger_are_empty_not_whole(adapter):
    """The failure that matters is a filter that silently does nothing."""
    narrowed = adapter.rows("temperature_compatible", subject="part:does-not-exist")
    assert narrowed["total"] == 0
    assert narrowed["rows"] == []


def test_unknown_names_are_answers_not_faults(adapter):
    with pytest.raises(KeyError):
        adapter.referent("part:does-not-exist")
    with pytest.raises(KeyError):
        adapter.rows("not_a_relation")
    with pytest.raises(KeyError):
        adapter.rows("acceptable_replacement", order="not_a_role")


def test_adapter_keeps_no_state_between_calls(adapter, world_path: Path):
    """The rule that would be broken first, and silently.

    A cached schema or row set is a second copy of the world with its own
    staleness. Checked by changing the world underneath and requiring the next
    read to see it — no invalidation call, because there is nothing to
    invalidate.
    """
    before = adapter.overview()["referents"]
    adapter._world.add_referent("part:ZZZ-probe", label="probe")
    assert adapter.overview()["referents"] == before + 1
    assert adapter.referent("part:ZZZ-probe")["label"] == "probe"


def test_origin_is_unknown_rather_than_an_error_when_unrecorded(world_path: Path, tmp_path):
    """A world compiled without the origin backfill still opens.

    `origin_for_assertion` raises there, and a canvas that 500s on a world it
    can otherwise draw teaches nothing. Reporting UNKNOWN puts the gap on
    screen, which is where it belongs.
    """
    stripped = tmp_path / "stripped.sqlite"
    stripped.write_bytes(world_path.read_bytes())
    sidecar = Path(str(stripped) + ".origins.json")
    sidecar.write_text(
        json.dumps({"world_id": "stripped", "assertions": {}}), encoding="utf-8"
    )
    with WorldExplorerAdapter(stripped) as opened:
        origins = opened.overview()["origins"]
        assert origins["UNKNOWN"] > 0
        assert origins.get("SEMANTIC", 0) == 0


# -- the budget ------------------------------------------------------------
#
# The read side turned out to be nearly free — the whole expansion menu for one
# referent, twenty relations scanned without an index, is under a millisecond on
# the largest world we have. These ceilings are set an order of magnitude above
# what was measured, so they catch a change of shape (an accidental full scan
# per row, a cache that stopped being a cache) rather than machine noise.
#
# Skipped when the S100 fixture has not been built: `scripts/build_world.py`
# takes three and a half minutes at that scale, which is not a thing to do
# inside a test run.

S100 = Path("data/worlds/bomS100.sqlite")


@pytest.mark.skipif(not S100.exists(), reason="build with scripts/build_world.py")
def test_read_path_stays_within_budget_at_s100():
    import time

    with WorldExplorerAdapter(S100) as adapter:
        def elapsed_ms(work) -> float:
            work()
            started = time.perf_counter()
            for _ in range(5):
                work()
            return (time.perf_counter() - started) / 5 * 1000

        assert elapsed_ms(adapter.schema) < 250
        assert elapsed_ms(lambda: adapter.referent("part:X160")) < 100
        assert elapsed_ms(lambda: adapter.rows("temperature_compatible", limit=200)) < 100
        assert elapsed_ms(adapter.referents) < 100
