"""What the explorer's read surface must keep answering.

These pin the four things §20 asks a front end to render faithfully — a binary
cross-source relation, a ternary semantic assertion with every role intact, an
unresolved obligation that is not a denial, and derived state distinguishable
from base — plus the rule that makes the adapter safe to keep: it holds nothing.

The world is built once per session from the sealed research path, into a tmp
directory. Building rather than reading `data/worlds/` on purpose: a test that
depends on a file someone generated by hand passes for reasons it cannot state.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from research.semantic_integration.domains.bom.operational_frontier.generate import (
    freeze_operational_frontier,
)
from research.semantic_integration.domains.bom.world_programming.construct import (
    construct_experimental_world,
)
from world_explorer.adapter import WorldExplorerAdapter


@pytest.fixture(scope="module")
def world_path(tmp_path_factory) -> Path:
    path = tmp_path_factory.mktemp("world") / "bomS1.sqlite"
    experimental = construct_experimental_world(path)
    freeze_operational_frontier(
        experimental.world.taskview, path.with_suffix(".demand.json")
    )
    experimental.world.close()
    return path


@pytest.fixture
def adapter(world_path: Path):
    with WorldExplorerAdapter(world_path) as opened:
        yield opened


def test_opens_without_being_told_the_view_id(world_path: Path):
    # The id belongs to the file. Requiring the caller to know it is how opening
    # a world becomes a guess that fails as if the file were corrupt.
    with WorldExplorerAdapter(world_path) as opened:
        assert opened.overview()["world_id"] == "bom-semantic-integration-c1"


def test_overview_accounts_for_every_assertion_by_construction_origin(adapter):
    overview = adapter.overview()
    assert overview["origins"]["SEMANTIC"] == 2
    assert overview["origins"]["MECHANICAL"] > 0
    assert overview["origins"]["DERIVED"] > 0
    assert sum(overview["origins"].values()) == overview["assertions"]
    assert "UNKNOWN" not in overview["origins"]


def test_schema_carries_the_facts_the_projection_needs(adapter):
    schema = {record["name"]: record for record in adapter.schema()}

    # §20 binary cross-source relation: collapses onto a filament.
    assert schema["listing_of"]["arity"] == 2

    # §20 ternary: three roles, all referents, none of them dropped.
    ternary = schema["acceptable_replacement"]
    assert ternary["arity"] == 3
    assert [role["name"] for role in ternary["roles"]] == [
        "new_part",
        "old_part",
        "context",
    ]
    assert all(role["referent"] for role in ternary["roles"])

    # A scalar role must be distinguishable, or §5.4 cannot decide what becomes
    # a card field instead of a node.
    assert any(not role["referent"] for role in schema["rated_voltage"]["roles"])


def test_role_kinds_are_observed_not_declared(adapter):
    """§7.1 is drawn in kinds the schema does not have.

    A role is typed REFERENT and nothing more, so `Part ─ listing_of ─
    SupplierListing` has to come from the ids the role has actually been filled
    with. Observation, not schema — and a role nothing has filled reports
    nothing rather than inventing a type the world never asserted.
    """
    schema = {record["name"]: record for record in adapter.schema()}
    kinds = {
        role["name"]: role["kinds"] for role in schema["listing_of"]["roles"]
    }
    assert kinds == {"listing": ["listing"], "part": ["part"]}

    ternary = {role["name"]: role["kinds"] for role in schema["acceptable_replacement"]["roles"]}
    assert ternary["context"] == ["context"]
    assert ternary["new_part"] == ternary["old_part"] == ["part"]

    # A scalar role has no kind at all — it never becomes a disc.
    scalar = next(
        role for role in schema["rated_voltage"]["roles"] if not role["referent"]
    )
    assert scalar["kinds"] == []


def test_derived_state_is_distinguishable_and_names_its_inputs(adapter):
    schema = {record["name"]: record for record in adapter.schema()}
    eligible = schema["eligible_part"]
    assert eligible["mode"] == "DERIVED"
    assert set(eligible["derivation"]["inputs"]) == {
        "lifecycle",
        "temperature_compatible",
        "voltage_compatible",
    }
    assert schema["listing_of"]["mode"] == "BASE"


def test_referent_separates_card_fields_from_relations_and_counts_them(adapter):
    referent = adapter.referent("part:X160")
    fields = {field["relation"]: field["value"] for field in referent["fields"]}
    assert fields["rated_voltage"] == 24
    assert fields["lifecycle"] == "discontinued"

    # Every card field is still an assertion — the inspector has to be openable
    # on it, or §5.4's convenience has quietly reinstated a property bag.
    for field in referent["fields"]:
        assert adapter.assertion(field["assertion_id"])["values"]

    relations = {item["name"]: item["count"] for item in referent["relations"]}
    assert relations["acceptable_replacement"] == 1
    assert "rated_voltage" not in relations


def test_assertion_exposes_origin_grounding_and_source_pointers(adapter):
    rows = adapter.rows("acceptable_replacement")["rows"]
    outdoor = next(
        row for row in rows if row["values"]["context"] == "context:outdoor_enclosure"
    )
    detail = adapter.assertion(outdoor["assertion_id"])

    assert detail["origin"] == "SEMANTIC"
    assert detail["values"] == {
        "new_part": "part:X110",
        "old_part": "part:X160",
        "context": "context:outdoor_enclosure",
    }

    # §8.5: a reader must get the file and the place in it, not a JSON string.
    pointers = {
        (item.get("native_handle"), item.get("native_location"))
        for item in detail["grounding"]
        if item["kind"] == "SOURCE"
    }
    assert ("bom.csv", "row 2 (bom_item=BOM-A)") in pointers
    assert ("engineering_notes.md", "lines 6-14 (ER-1)") in pointers


def test_unresolved_obligation_is_not_a_denial(adapter):
    demand = adapter.demand()
    assert demand["purpose"]["id"] == "viable_replacement"
    unresolved = [
        item for item in demand["obligations"] if item["state"] == "UNRESOLVED"
    ]
    assert {"new_part": "part:X110", "old_part": "part:X160", "context": "context:indoor_panel"} in [
        item["values"] for item in unresolved
    ]
    # The world holds no tuple for it, and the frontier says so without the
    # relation acquiring a false one.
    assert all(item["assertion_id"] is None for item in unresolved)


def test_demand_is_absent_rather_than_empty_without_a_purpose(world_path: Path, tmp_path):
    bare = tmp_path / "bare.sqlite"
    bare.write_bytes(world_path.read_bytes())
    with WorldExplorerAdapter(bare) as opened:
        # No purpose loaded is not the same claim as no open questions.
        assert opened.demand() is None


def test_rows_page_and_order_in_sql(adapter):
    first = adapter.rows("temperature_compatible", limit=1, order="part")
    second = adapter.rows("temperature_compatible", limit=1, offset=1, order="part")
    assert first["total"] > 1
    assert len(first["rows"]) == 1
    assert first["rows"][0]["assertion_id"] != second["rows"][0]["assertion_id"]
    assert first["rows"][0]["values"]["part"] <= second["rows"][0]["values"]["part"]

    descending = adapter.rows("temperature_compatible", limit=1, order="part", descending=True)
    assert descending["rows"][0]["values"]["part"] >= first["rows"][0]["values"]["part"]


def test_unknown_names_are_answers_not_faults(adapter):
    with pytest.raises(KeyError):
        adapter.referent("part:does-not-exist")
    with pytest.raises(KeyError):
        adapter.rows("not_a_relation")
    with pytest.raises(KeyError):
        adapter.rows("acceptable_replacement", order="not_a_role")


def test_adapter_keeps_no_state_between_calls(adapter, world_path: Path):
    """The rule that would be broken first, and silently.

    A cached schema or row set is a second copy of the world with its own
    staleness. Checked by changing the world underneath and requiring the next
    read to see it — no invalidation call, because there is nothing to
    invalidate.
    """
    before = adapter.overview()["referents"]
    adapter._world.add_referent("part:ZZZ-probe", label="probe")
    assert adapter.overview()["referents"] == before + 1
    assert adapter.referent("part:ZZZ-probe")["label"] == "probe"


def test_origin_is_unknown_rather_than_an_error_when_unrecorded(world_path: Path, tmp_path):
    """A world compiled without the origin backfill still opens.

    `origin_for_assertion` raises there, and a canvas that 500s on a world it
    can otherwise draw teaches nothing. Reporting UNKNOWN puts the gap on
    screen, which is where it belongs.
    """
    stripped = tmp_path / "stripped.sqlite"
    stripped.write_bytes(world_path.read_bytes())
    sidecar = Path(str(stripped) + ".origins.json")
    sidecar.write_text(
        json.dumps({"world_id": "stripped", "assertions": {}}), encoding="utf-8"
    )
    with WorldExplorerAdapter(stripped) as opened:
        origins = opened.overview()["origins"]
        assert origins["UNKNOWN"] > 0
        assert origins.get("SEMANTIC", 0) == 0


# -- the budget ------------------------------------------------------------
#
# The read side turned out to be nearly free — the whole expansion menu for one
# referent, twenty relations scanned without an index, is under a millisecond on
# the largest world we have. These ceilings are set an order of magnitude above
# what was measured, so they catch a change of shape (an accidental full scan
# per row, a cache that stopped being a cache) rather than machine noise.
#
# Skipped when the S100 fixture has not been built: `scripts/build_world.py`
# takes three and a half minutes at that scale, which is not a thing to do
# inside a test run.

S100 = Path("data/worlds/bomS100.sqlite")


@pytest.mark.skipif(not S100.exists(), reason="build with scripts/build_world.py")
def test_read_path_stays_within_budget_at_s100():
    import time

    with WorldExplorerAdapter(S100) as adapter:
        def elapsed_ms(work) -> float:
            work()
            started = time.perf_counter()
            for _ in range(5):
                work()
            return (time.perf_counter() - started) / 5 * 1000

        assert elapsed_ms(adapter.schema) < 250
        assert elapsed_ms(lambda: adapter.referent("part:X160")) < 100
        assert elapsed_ms(lambda: adapter.rows("temperature_compatible", limit=200)) < 100
        assert elapsed_ms(adapter.referents) < 100
