snapshot: deployable-map-2026-08-30
services:
  service:checkout:
    component: component:checkout-json
  service:reporting:
    component: component:reporting-json
  service:partner-gateway:
    component: component:partner-json
  service:catalog-search:
    component: component:catalog-search
  service:billing:
    component: component:billing-codec

